apiVersion: "v1"
kind: "Pod"
metadata:
  name: "podman-service"
  namespace: "podman"
spec:
  containers:
    env:
    - name: "REGISTRY_AUTH_FILE"
      value: "/home/podman/.docker/config.json"
    - name: "DOCKER_CONFIG"
      value: "/home/podman/.docker"
    - name: "DOCKER_HOST"
      value: "tcp://localhost:8888"
    image: "ggcr.io/raqqun/podman-service-ci:4.9.3"
    imagePullPolicy: "Always"
    name: "podman-service"
    ports:
    - containerPort: 8888
  #   volumeMounts:
  #   - mountPath: "/home/podman/.docker"
  #     name: "docker-config"
  #     readOnly: false
  #   workingDir: "/home/podman/"
  # volumes:
  # - name: "docker-config"
  #   secret:
  #     secretName: "docker-auth-conf"
# ---
# apiVersion: v1
# data:
#   config.json: 
# kind: Secret
# metadata:
#   name: dokcer-auth-conf
#   namespace: podman
# type: Opaque